/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCiudades.java
 *
 * Created on 11-feb-2011, 17:46:59
 */

package Presentacion;

import Presentacion.Sistema;
import javax.swing.JFrame;


/**
 *
 * @author edu
 */
public class frmCiudades extends javax.swing.JFrame {   
    Sistema s = new Sistema();
    /** Creates new form frmCiudades */

    public frmCiudades() {
        initComponents();
        setTitle("ManchaViajes: Ciudades");
        listCiudades.setListData(frmPrincipal.agencia.Ciudades.toArray());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnHotelyTrans = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCiudades = new javax.swing.JList();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevo.setText("Nueva");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevaCiudad(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        btnHotelyTrans.setText("Ver Hoteles \ny Transportes"); // NOI18N
        btnHotelyTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHotelyTransMouseClicked(evt);
            }
        });

        btnAtras.setText("Volver");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        listCiudades.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCiudades);

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarNuevaCiudad(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(btnHotelyTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnAtras)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHotelyTrans)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaCiudad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevaCiudad
        frmCrearCiudad c = new frmCrearCiudad();
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        c.setVisible(true);
    }//GEN-LAST:event_NuevaCiudad

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        try{
            frmPrincipal.agencia.Ciudades.remove(listCiudades.getSelectedIndex());
            frmCiudades.listCiudades.setListData(frmPrincipal.agencia.Ciudades.toArray());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnHotelyTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotelyTransMouseClicked
        try{
            int indice=listCiudades.getSelectedIndex();
            frmTransyHotel ht = new frmTransyHotel(indice);
            ht.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ht.setVisible(true);
        }catch(Exception ex){}
    }//GEN-LAST:event_btnHotelyTransMouseClicked

    private void btnEditarNuevaCiudad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarNuevaCiudad
        frmEditarCiudad ed = new frmEditarCiudad(listCiudades.getSelectedIndex());
        ed.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ed.setVisible(true);
    }//GEN-LAST:event_btnEditarNuevaCiudad

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCiudades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnHotelyTrans;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList listCiudades;
    // End of variables declaration//GEN-END:variables

}
